### PR TITLE
Provide mechanism for configuring and extending lynx-docs at runtime

### PR DESCRIPTION
**Pull request by ansongoldade**
- A 'config' module can be specified with a switch or a .lynxdocsrc value. The module will be called after lynx-docs is configured but before the `export` or `start` process begins. The module will be provided with a reference to the current options that lynx-docs was started with along with a reference to the lynx-docs instance that is running. The module can further configure or extend the behavior of the running instance.
- Added some code clean-up and renaming where it seemed appropriate.

### CODE REVIEW

**Comment by ansongoldade** [comment]
Reference to issue #119

**Comment by ansongoldade** [comment]
Resolves #116

**Comment by ansongoldade** [comment]
Here is a snippet of the content that will be in the wiki page "Runtime configuration with custom modules". There will be more content in the article to detail the objects and functions attached to the running server and other changes to the wiki to link to this content. The goal of the snippet is to provide more context for evaluating the code changes.

---
In addition to the configuration options provided by [command line parameters](./command-line-parameters) and the [.lynxdocsrc](./Run-control-(.lynxdocsrc)) run control file, you my configure a running `lynx-docs` server instance with a node module(s). The module(s) is called after the [command line parameters](./command-line-parameters) and the [.lynxdocsrc](./Run-control-(.lynxdocsrc)) run control file are processed. The module(s) are specified by the `--config` [command line parameter](./command-line-parameters) or the `config` [run control](./Run-control-(.lynxdocsrc)) value and will be resolved relative to the process working directory (`process.cwd()`).

A configuration module must export a function that will be called with the running `lynx-docs` server instance and the options it was configured with. For example:

```javascript
//custom partial resolution example
module.exports = exports = function customizePartialResolution(options, lynxDocs) {
  var pattern = new RegExp("\\w+_\\w+");
  var originalResolver = lynxDocs.jsonTemplates.partials.resolving.resolvePartialFromName;

  lynxDocs.jsonTemplates.partials.resolving.resolvePartialFromName = function(basePath, partialName) {
    return pattern.test(partialName) ? 
      customResolver(basePath, partialName) :
      originalResolver(basePath, partialName);
  }
}
```

**Comment by danmork** [comment]
Thanks. So is that the primary goal of this PR – to mainstream the type of extension that terms/vocabulary are currently making? Which is a narrower goal than the goal statements I copied/pasted into Slack (e.g. nothing from the `start` server subsystem is exported on the app instance so this feature doesn't offer any enhancement to configuration of that subsystem).

**Comment by ansongoldade** [comment]
My goal for this PR was to create a mechanism to override the `lib` area of `lynx-docs` (`jsonTemplates` and `export`).  I felt comfortable in how to expose a server instance to a module and in how to expose the `jsonTemplates` and `export` areas within `lib`. I was less sure about how to create an extensibility story around the `start` command, `export` command, and the realm calculations. Therefore I decided to propose the this PR, with the limited scope, to solve for the existing customization scenarios. My thinking was that either based on need, or someone having a clearer vision than I about how to expose those other areas, additional work would be done to finish out the entire capability at a later time.

**Comment by danmork** [comment]
Thanks. That helps.

**Comment by ansongoldade** [comment]
Working through some of the wiki documentation. Adding a portion of that content for further context.

---
### `lynxDocs`
* `jsonTemplates` - reference to module used for converting template content to an expanded format that is transformed to handlebars for biding data.
* `export` - reference to module that exports template content to handlebars or application/lynx+json content. When exporting application/lynx+json documents, templates are processed according to the application/lynx+json specification, the templates are converted to handlebars, and data is bound to the handlebars content to create a document.

### `lynxDocs.jsonTemplates`
* `partials` - module responsible for resolving and processing partials
* `expandTokens` function that creates an expanded template object from the input template object.
  * `function(template)`
  * `template` - the template to expand
* `toHandlebars` - function that converts an expanded template to handlebars content.
  * `function(template, options)`
  * `template` - template to convert to handlebars format
  * `options` - handlebars options that were configured using command line parameters or run control file. 
* `templateKey` - module used to process the keys in template content.
* `validators` - module containing functions to validate template content.
* `process` - function that runs all of the json templates pipeline against a template source.
  * `function(source, resolvePartialStartPath, options)`
  * `source` - the template source to process.
  * `resolvePartialStartPath` - the path where to begin resolving partials included in the template content.
  * `options` - the options the server was configured with.

### `lynxDocs.jsonTemplates.partials`
* `expanding` - module responsible for expanding the partial template syntax.
* `key` - module that parses key names with partial syntax rules
* `resolving` - module responsible for resolving partials.
* `applyParameters` - function that applies the parameter values that a partial was called with to the partial.
  * `function(partial, parameters)`
  * `partial` - the partial object to apply the parameters to.
  * `parameters` - the parameters to apply to the partial.

**Comment by ansongoldade** [comment]
@danmork Regarding the "Thanks. That helps" comment. Are you still reviewing the PR or is that comment meant to indicate that with the clarification you understand and approve the changes in the PR?

**Comment by danmork** [comment]
I’m not listed as a reviewer on this PR so I cannot approve it, but, if I were, I would.

**Pull request merged**
